### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by batoorsohail** [frempongdev/Leaderboard#3]
### Highlights 🏅 
- Your code is clean 😃 
- Good commits 🏆 
- No Linters error 👍

**Comment by Kingno3l** [comment]
Great work @frempongdev 😃

**Comment by frempongdev** [comment]
Thank You all @batoorsohail and @Kingno3l. Taking a look at my project means a lot to me. 😉

**Comment by frempongdev** [comment]
Thank You all @batoorsohail and @Kingno3l. Taking a look at my project means a lot to me. 😉
